### ISSUE TITLE
i18n 対応

### ISSUE THREAD

**Issue by mikoto2000** [mikoto2000/ya-rails-template#1]
# 方針

モデルに関するものは、 `<MODEL_NAME>.human_attribute_name(:<COLUMN_NAME>)` を使って変換する。

変換の設定ファイルは以下のようになる。

```yaml
# config/locales/ja.yml
ja:
  activerecord:
    models:
      account: アカウント
    attributes:
      account:
        name: 名前
        role_id: 権限
        expiration_date: 期限
        created_at: 作成日
        updated_at: 更新日
```

その他メッセージは、適当にラベルを決めて `t(:<LABEL_NAME>)` で変換させる。

# 対象

- [x] : index
    - [x] : タイトル
    - [x] : 検索条件設定
    - [x] : 検索条件フォーム・ラベル
    - [x] : 検索ボタン
    - [x] : Clear ボタン
    - [x] : 一覧のテーブルヘッダ
    - [x] : Delete ボタン
    - [x] : 削除時のダイアログ
    - [x] : ページネーションのコントローラー
    - [x] : 1 ページごとの表示数を変更するところ
- [x] : show
    - [x] : タイトル
    - [x] : ラベル
    - [x] : Edit this model リンク
    - [x] : Back to model リンク
    - [x] : Destroy this account ボタン
    - [x] : 削除時のダイアログ
- [x] : edit
    - [x] : タイトル
    - [x] : ラベル
    - [x] : 更新するボタン
    - [x] : エラー表示
    - [x] : Show this model リンク
    - [x] : Back to model リンク
- [x] : new
    - [x] : タイトル
    - [x] : ラベル
    - [x] : 登録するボタン
    - [x] : エラー表示
    - [x] : Back to model リンク
- [ ] : デフォルト辞書ファイルの配置
